Repository nanas773/kpt, pull requests merged in 2021-05, with the labels that each got.

#33 Web containerのwork directoryを修正
  infra/docker/nginx/Dockerfile
Labels: bug

#34 use docker compose command
  Makefile
Labels: enhancement

#35 IssueとPR用のテンプレートを追加
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
