Repository nanas773/kpt, pull requests merged in 2021-06, with the labels that each got.

#32 [モック]所属チーム一覧画面の追加
  app/Http/Controllers/TeamController.php
  resources/components/pages/team/Index.vue
  resources/js/pages/team/index.js
  resources/views/team/index.blade.php
  routes/web.php
  webpack.mix.js
Labels: Mock

#31 [モック]プロジェクト画面の追加
  app/Http/Controllers/ProjectController.php
  resources/components/pages/project/Detail.vue
  resources/components/pages/project/Index.vue
  resources/js/pages/project/detail.js
  resources/js/pages/project/index.js
  resources/views/project/detail.blade.php
  resources/views/project/index.blade.php
  routes/web.php
  webpack.mix.js
Labels: Mock

#48 Teams-Usersテーブル間のDB構造の修正
  database/migrations/2021_06_12_020527_delete_colum_from_teams.php
Labels: invalid

#49 Problem作成のリクエストが送信できるようにした
  app/Http/Controllers/Api/ProblemController.php
  resources/components/pages/project/Detail.vue
  routes/api.php
Labels: enhancement
